name: Composer
on: [pull_request]

jobs:
  php-cs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: latest
      - uses: docker://php:7.4
        with:
          args: vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: latest
      - name: PHPStan
        uses: docker://php:7.4
        with:
          args: vendor/bin/phpstan analyse -c phpstan.neon

  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: latest
      - uses: docker://php:7.4
        with:
          args: vendor/bin/phpstan analyse -c phpstan.neon